### ISSUE TITLE
retrieves user specific fields from Active directory with Laravel

### ISSUE THREAD

**Issue by larhemouchi** [stevebauman/stevebauman-blog#7]
- Laravel Version: 7.3
- LdapRecord Version: 2.0
- PHP Version: 7.3
- LDAPRecord Type: 

Is it possible to obtain the fields (name, first name, telephone number, office) from the active directory, in order to feed a table.
I am a beginner. If you can help me.

Thank you

**Comment by stevebauman** [comment]
Hi @larhemouchi,

Yes absolutely. You can import any LDAP objects into your directory via the synchronizer and importer:

https://ldaprecord.com/docs/laravel/v2/importing/

Are you looking to authenticate LDAP users in your Laravel application, or are you looking to import LDAP data into your Laravel applications database?

**Comment by larhemouchi** [comment]
A thousand thanks for your help, you saved me. It's been a long time that I have been looking without an answer.
i am grateful for you.

Thank youuuuuuuuuuuuuuuuu <3 <3 <3

**Comment by stevebauman** [comment]
Happy to help @larhemouchi! ❤️

**Comment by larhemouchi** [comment]
I would like to thank you also for the package that you have developed it's really great  (Y)(Y)(Y)(Y)

**Comment by stevebauman** [comment]
Thank you for your kind words @larhemouchi! I'm so glad to hear that you enjoy using it 😄

**Comment by larhemouchi** [comment]
It is really great, in the establishment where I work, I will integrate this authentication method in all the applications.

A thousand thanks to you
